version: 2

models:
  - name: dim_company
    description: "Unique companies with job posting stats"
    columns:
      - name: company_id
        description: "MD5 hash of company name"
        tests:
          - unique
          - not_null

  - name: dim_location
    description: "Unique locations"
    columns:
      - name: location_id
        description: "MD5 hash of location"
        tests:
          - unique
          - not_null

  - name: dim_date
    description: "Date dimension"
    columns:
      - name: date_id
        description: "MD5 hash of date"
        tests:
          - unique
          - not_null

  - name: fact_job_postings
    description: "One row per job posting"
    columns:
      - name: job_id
        description: "Unique job identifier"
        tests:
          - unique
          - not_null
      - name: title_normalized
        tests:
          - not_null
      - name: company_id
        tests:
          - not_null